#!/usr/bin/env bash

# Function to display usage information
usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if less than 4 parameters are passed
if [ "$#" -ne 4 ]; then
    usage
else
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
