#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages

apt-get update -y
apt-get install nginx -y
sudo ufw 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.html'
service nginx restart
