#!/usr/bin/env bash
# Web servers are the piece of software generating and serving HTML pages

sudo apt-get update
sudo apt-get install nginx -y
sudo ufw 'Nginx HTTP'
sudo service nginx restart
sudo service nginx reload
