#!/usr/bin/env bash
# Configure your Nginx serverso that HTTP response contains a custom header

sudo apt-get update -y
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

hostname=$(HOSTNAME)

# Nginx configuration to include custom header
sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
        add_header X-Served-By $HOSTNAME;
    }
}

# Reload Nginx
service nginx restart
