#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

# modify default Nginx configuration to return "Hello World!" at root URL
sudo bash -c 'echo "Hello World!" > /var/www/html/index.html'
sudo bash -c 'echo "Ceci n'\''est pas une page" > /var/www/html/404.html'
# append a youtube page to redirect to using /redirect_me
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/@dominicmusyoki804 permanent;' /etc/nginx/sites-available/default

# append custom 404 page
sudo sed -i '/listen 80 default_server/a error_page 404 /404.html;' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart
