#!/usr/bin/env bash
# script that Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  siren
        bind *:80
        mode http
        default_backend app
backend app
        balance roundrobin
        server 247218-web-01 100.25.160.4:80 check
        server 247218-web-02 100.25.3.149:80 check
"
sudo echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
sudo echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
