#!/usr/bin/env bash

# Check if the number of arguments is correct
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the argument
ip_address=$1

# Ping the IP address 5 times
echo "Pinging $ip_address..."
ping -c 5 "$ip_address"
