#!/usr/bin/env bash
# script that ensure Nginx is running and listening on port 80

sudo apt-get update -y
sudo apt-get install -y nginx

# configuration to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx server
sudo service nginx restart
