#!/usr/bin/env bash
# script that displays username, user id and home directory for eac line of /etc/paswwd

passwd_file="/etc/passwd"

if [ -e "$passwd_file" ]; then
  while IFS=: read -r username _ uid _ _ home _; do
    echo "Username: $username"
    echo "User ID: $uid"
    echo "Home Directory: $home"
    echo
  done < "$passwd_file"
else
  echo "Error: /etc/passwd file does not exist."
fi
