#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop

count=0

while [ $count -lt 10 ]; do
    ((count++))

    # Check for the 9th iteration
    if [ $count -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
done
