#!/usr/bin/env bash
# Displays Best School from 1 to 10 with exceptions at 4th & 8th loop

counter=1
while [ "$counter" -le 10 ]
do
	if [ "$counter" -eq 4 ];
	then
		echo "Bad Luck"
	elif [ "$counter" -eq 8 ];
	then
		echo "Good Luck"
	else
		echo "Best School"
	fi
	(("counter += 1"))
done
