#!/usr/bin/env bash
# Display 1 to 20 with exceptions in 4th 9th and 17th loop

count=0

while [ $count -lt 20 ]; do
    ((count++))

    case $count in
        4)
            echo "$count and then bad luck from China"
            ;;
        9)
            echo "$count and then bad luck from Japan"
            ;;
        17)
            echo "$count and then bad luck from Italy"
            ;;
        *)
            echo $count
            ;;
    esac
done
