#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash

for file in *; do
  if [ -f "$file" ] && [[ "$file" != .* ]]; then
    name=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name"
  fi
done
