#!/usr/bin/env bash
# Displays the contents of the current directory in list format.

for file in *; do
    if [[ ! "$file" == .* && "$file" == *-* ]]; then
        name_after_dash=$(echo "$file" | cut -d '-' -f 2-)
        echo "$name_after_dash"
    fi
done
