#!/usr/bin/env bash
# Displays content of current directory in a list format

for file in *; do
  if [ -f "$file" ] && [[ "$file" != .* ]]; then
    name=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name"
  fi
done
