#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01

sudo apt-get install -y ufw
sudo ufw status
sudo ufw default allow outgoing -y
sudo ufw default deny incoming -y
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
echo "y" | sudo ufw enable
