#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
# Requirements:
#    localhost resolves to 127.0.0.2
#    facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i 's/^127.*localhost$/127.0.0.2 localhost/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
