#!/usr/bin/env bash
# Configure an Ubuntu server

# Check if the script is running inside Docker
if [ ! -f "/.dockerenv" ]; then
    echo "Error: This script should be run inside Docker."
    exit 1
fi

# Check if the script is running on Ubuntu
if [ "$(cat /etc/os-release | grep ^NAME= | awk -F\" '{print $2}')" != "Ubuntu" ]; then
    echo "Error: This script should be run on Ubuntu."
    exit 1
fi

cp /etc/hosts ~/hosts.new
sed -i 's/^127.*localhost$/127.0.0.2 localhost/' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
