#!/usr/bin/env bash
# Define the server address
SERVER_ADDRESS="34.229.56.68"

# Use ssh with the required flags to connect to the server
ssh -i ~/.ssh/school -o StrictHostKeyChecking=no ubuntu@$SERVER_ADDRESS
